name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: 'actions/checkout@v2'

    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.gcp_credentials }}'

    - id: 'deploy-model'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'Test'
        runtime: 'go116'

    - id: 'deploy-transaction'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'CreateTransaction'
        runtime: 'go116'
